# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - { os: macos-latest,   shell: bash  }
          - { os: ubuntu-latest,  shell: bash  }
          - { os: windows-latest, shell: msys2, sys: mingw64 }
    defaults:
      run:
        shell: ${{ matrix.shell }} {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          install: git zip
          pacboy: gcc:p

      - name: Build
        run: |
          ./batch.sh
          export platform=$(echo ${{ runner.os }} | awk '{print tolower($0)}')
          zip -r "libs-${platform}-x64.zip" dist

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: libs-*.zip
